import type { Metadata } from "next";
import "./globals.scss";
import Link from "next/link";
import cls from './Layout.module.scss';

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <nav className={cls.container}>
                    <Link href="/">Home</Link>
                    <Link href="/todos">Todos</Link>
                    <Link href="/about">About</Link>
                    <Link href="/posts">Posts</Link>
                </nav>
                {children}
            </body>
        </html>
    );
}
